on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Tag a release'
        type: boolean
        required: false
        default: false

name: Download latest libs from CRAN

jobs:
  download:
    # OS matters because we copy 'cmake' and 'zstd' binaries from homebrew
    strategy:
      matrix:
        os: [macos-15, macos-15-intel]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare git
        run: |
          git config --global user.email '74155986+r-universe[bot]@users.noreply.github.com'
          git config --global user.name  'r-universe[bot]'

      - name: Checkout
        uses: actions/checkout@v7

      - name: Download libraries
        run: ./.github/workflows/download.sh

      - uses: actions/upload-artifact@v7
        with:
          name: cranlibs-${{ matrix.os }}
          path: opt

  Combine:
    if: ${{ github.event.inputs.release == 'true' }}
    runs-on: ubuntu-latest
    needs: download
    steps:
      - uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: Create xz and zstd archives
        id: bundles
        run: |
          mkdir opt
          mv R opt/
          chmod +x opt/R/*/bin/*
          tar cfJ cranlibs-everything.tar.xz opt
          tar -I 'zstd --ultra -22' -cf cranlibs-everything.tar.zst opt
          echo "date=$(date +%F)" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.bundles.outputs.date }}
          files: cranlibs-everything.*
